export ALLOW_MISSING_DEPENDENCIES=true
export USE_NINJA=true
export LLVM_ENABLE_THREADS=1
export WITH_DEXPREOPT=false

add_lunch_combo potato_f500_usu-userdebug
add_lunch_combo potato_f500_usu-user
add_lunch_combo potato_f500_usu_eng

add_lunch_combo potato_h810_usu-userdebug
add_lunch_combo potato_h810_usu-user
add_lunch_combo potato_h810_usu_eng

add_lunch_combo potato_h811_usu-userdebug
add_lunch_combo potato_h811_usu-user
add_lunch_combo potato_h811_usu_eng

add_lunch_combo potato_h812_usu-userdebug
add_lunch_combo potato_h812_usu-user
add_lunch_combo potato_h812_usu_eng

add_lunch_combo potato_h815-userdebug
add_lunch_combo potato_h815-user
add_lunch_combo potato_h815_eng

add_lunch_combo potato_h815_usu-userdebug
add_lunch_combo potato_h815_usu-user
add_lunch_combo potato_h815_usu_eng

add_lunch_combo potato_ls991_usu-userdebug
add_lunch_combo potato_ls991_usu-user
add_lunch_combo potato_ls991_usu_eng

add_lunch_combo potato_us991_usu-userdebug
add_lunch_combo potato_us991_usu-user
add_lunch_combo potato_us991_usu_eng

add_lunch_combo potato_vs986_usu-userdebug
add_lunch_combo potato_vs986_usu-user
add_lunch_combo potato_vs986_usu_eng

